### ISSUE TITLE
Any plans for a Node.js implementation?

### ISSUE THREAD

**Issue by andrewconnell** [Microsoft/ApplicationInsights-Kubernetes#104]
Any plans to ship this for more than just .NET Core? Node.js?

**Comment by xiaomi7732** [comment]
@andrewconnell thanks for your question! We don't have a plan for node.js or other languages at this moment. That said, have you check out the [Application Insights for Node.js](https://github.com/Microsoft/ApplicationInsights-node.js)? Will that mean your needs?

**Comment by andrewconnell** [comment]
Yes... I am already using it. I use Node.js (TypeScript) in my containers and was looking for the same container specific monitoring for an ACS cluster that you have for .NET Core... guess its going to be custom them... thanks.
