### ISSUE TITLE
Seems like just support ASP.NET core and .NET core?

### ISSUE THREAD

**Issue by DanielWangZhanggui** [Microsoft/ApplicationInsights-Kubernetes#118]
From the doc description, it seems  like just support ASP.NET core and .NET core? Do we have plan to support other programming languages?

All the best,
Daniel

**Comment by xiaomi7732** [comment]
@DanielWangZhanggui Thanks for your inquiry. At this point, only C# is supported.

It won't change the answer but would you please tell us what language support are you looking for?

Thanks!

**Comment by xiaomi7732** [comment]
@DanielWangZhanggui Thanks for the clarification.
Unfortunately, this is Application Insights based and is built upon specific languages.
Thanks again for the ask!
