### ISSUE TITLE
FAQ: support for AKS managed service?

### ISSUE THREAD

**Issue by waheedhussain** [microsoft/ApplicationInsights-Kubernetes#122]
Hi,

Does this SDK support the AKS managed service (link below)? or is it only to be used for Kubernetes on ACS?

https://docs.microsoft.com/en-us/azure/aks/intro-kubernetes

Thanks

**Comment by xiaomi7732** [comment]
@waheedhussain Thanks for your question. Application Insights for Kubernets can run in both ACS & AKS with no problem.
As a matter of fact, ACS was our testing environment and now it is AKS.

If there's any specific issue in regarding running application insights for K8s in AKS, please feel free to open new issues.

**Comment by waheedhussain** [comment]
ok....thanks.....we will start using this with AKS soon so just wanted to double check.

Waheed

**Comment by xiaomi7732** [comment]
Thanks for the check. I'll lock this conversation since there's no further action item. Feel free to open new issues.
