### ISSUE TITLE
Can this work on arbitrary K8s cluster or in Azure only?

### ISSUE THREAD

**Issue by mrmartan** [Microsoft/ApplicationInsights-Kubernetes#129]
Hello.

As the title suggests. If it can work on custom on premises k8s clusters, what are the prerequisites (like kubernetes controller version)?

I am trying this with our cluster and I am getting a mix of failures, timeouts and successes. I am not getting any K8s properties in my traces (except the SDK version). Sample trace captured by AppInsights below:

**Request Properties**
Event time	7/30/2018, 1:44:55 PM	
Request name	GET /odata/DocumentItems	
Response code	200	
Successful request	True	
Response time	832.7 ms	
Request URL	http://finis-api.k8s.*****/odata/DocumentItems?$filter=Year eq 2018&$top=100&$orderby=DocumentNumber desc	
Request Id	|36d7a397-45ca10cb6fe98f94.	
**SDK version	ai-k8s:1.0.0.8**	
Operation Id	36d7a397-45ca10cb6fe98f94	
Parent Id	36d7a397-45ca10cb6fe98f94	
Client IP address	0.0.0.0	
Sample rate	1	
Performance	500ms-1sec	
Operation name	GET /odata/DocumentItems	
Application version	1.0.0.0	
Device type	PC	
Cloud role instance	  finis-api-1327148757-5zf1v	
Telemetry type	  request	
**Custom Data**
AspNetCoreEnvironment	Dev

EDIT:
Some more info (not really sure how to extract raw data from AppInsights - only just started with it)
![image](https://user-images.githubusercontent.com/2376580/43396998-b0a3c078-9403-11e8-9e98-d85be41dc614.png)

I am using (ASP).NET Core 2.1.2 and linux containers

**Comment by xiaomi7732** [comment]
@mrmartan Thanks for the asking. AI.K8s shall be able to work with on a custom on-premises hosts.

There are several interesting info in the snapshot you provided:
1. Query Kubernetes Environment timeout indicates the application doesn't have permission to query the K8s master. By chance, is that an RBAC enabled cluster?
2. Hosting startup assembly exception indicates the hosting startup is not working. But then you shall not have the SDK version set. Are you using hosting startup or not? Meaning:
  2.1 Do you add the reference to the hosting startup NuGet package?
  2.2 Do you call EnableKubernetes() in the startup code?

Thanks,
Saar

**Comment by mrmartan** [comment]
@1) It seems it is. Although it is a development cluster and it is a bit of a mess. I suspected permissions myself. The problem was that there was a bunch of dependency successes. See here: 
![image](https://user-images.githubusercontent.com/2376580/43581860-b21522d6-965a-11e8-86b6-71b6f601aa65.png)
@2.1) I am using `Microsoft.ApplicationInsights.Kubernetes.HostingStartup Version="1.0.0-beta8"` and setting env variable such as this:
```
name: ASPNETCORE_HOSTINGSTARTUPASSEMBLIES
value: "Microsoft.ApplicationInsights.Profiler.AspNetCore; Microsoft.ApplicationInsights.Kubernetes.HostingStartup"
```
@2.2) No, I am not calling that.

**Comment by xiaomi7732** [comment]
@mrmartan Hmm, yes, those are successful calls... Could you please try enable the verbose logs by following [Self-Diagnostics](https://github.com/Microsoft/ApplicationInsights-Kubernetes/wiki/%5BAdvanced%5D-How-to-enable-self-diagnostics-for-ApplicationInsights.Kubernetes#enable-self-diagnostics) and see if there are anything indicates.
With regarding properly setup permission for RBAC, reference exmaple here:
[>>> RBAC Configure Example](https://github.com/Microsoft/ApplicationInsights-Kubernetes/tree/develop/examples/BasicUsage_clr21_RBAC#setup-the-default-service-account-for-rbac-enabled-cluster)

**Comment by mrmartan** [comment]
I have tried that earlier and only saw some successes and auth tokens. I did not send those logs to azure so I don't have them anymore. Will try again.

In the meantime. Is it expected that there is so many of the calls, i.e. 2 per second?

**Comment by mrmartan** [comment]
I've sent you the log file to your email address in GitHub from mr.martan@outlook.com

**Comment by mrmartan** [comment]
I have also added the RBAC configuration according to your example. Still all I can see targeting the k8s cluster are the /pods queries
![image](https://user-images.githubusercontent.com/2376580/43652597-ec5d3cd0-9745-11e8-8d0c-9329357594f2.png)

![image](https://user-images.githubusercontent.com/2376580/43652660-1b22cbb6-9746-11e8-8dbe-6cabb967b98b.png)

**Comment by xiaomi7732** [comment]
@mrmartan Thanks for mailing me the logs. I have replied the mail with details. Basically, I don't see errors in the log, it means the permission should be fine.
There are some interesting points:
1. You are using [Application Insights Profiler](https://github.com/Microsoft/ApplicationInsights-Profiler-AspNetCore) at the same time - since that is a relatively new library, there might be scenarios that have bugs in it.
2. You are using hosting startup - hosting startup is good to use for projects that you don't want to change existing code. In this case, though, it adds some complexity for troubleshooting.
All that said, I put some troublehsooting suggestions in the mail already. Please check it out and let's see what we will get.

**Comment by xiaomi7732** [comment]
Hey @mrmartan I have sent you a mail on 8/4 with a debugging image. Have you got chance to try it out?

**Comment by mrmartan** [comment]
Not yet. Sry.

Yesterday it occurred to me that you are not saying anything about K8s version compatibility with this package. Is there any? Or it this expecting the latest version? Could that be the source of problems?

**Comment by xiaomi7732** [comment]
@mrmartan Thanks for the ask. `ApplicationInsights.Kubernetes` should run on K8s 1.7.8 and above. That said, there's still chance for one to run it in older version successfully.
What is the version that you used?

**Comment by mrmartan** [comment]
I am sorry I am way too busy right now. I **will** get back to this.

**Comment by xiaomi7732** [comment]
No problem! I'll close this conversation for now. Feel free to reopen or start a new one at any time!
