### ISSUE TITLE
Microsoft.ApplicationInsights.DependencyCollector locks in specific version of application insights package

### ISSUE THREAD

**Issue by timmydo** [Microsoft/ApplicationInsights-Kubernetes#135]
I was trying to use app insights 2.8.0-beta1 and app insights k8s 1.0.0-beta9 nuget package. But the k8s nuget package depends on Microsoft.ApplicationInsights.DependencyCollector and the dependency collector depends on Microsoft.ApplicationInsights (= 2.7.2). I'm not sure the best place to report this issue.
```
    NU1608: Detected package version outside of dependency constraint: Microsoft.ApplicationInsights.DependencyCollector
 2.4.1 requires Microsoft.ApplicationInsights (= 2.4.0) but version Microsoft.ApplicationInsights 2.8.0-beta1 was resolved
```

**Comment by brahmnes** [comment]
Hi @timmydo,

It looks like Microsoft.ApplicationInsights.DependencyCollector does depend on Microsoft.ApplicationInsights 2.8.0-beta1
https://www.nuget.org/packages/Microsoft.ApplicationInsights.DependencyCollector/2.8.0-beta1

Are you using 2.8.0-beta1 version of Microsoft.ApplicationInsights.DependencyCollector?

**Comment by timmydo** [comment]
ah looks like I need to manually reference dependency collector, otherwise nuget chooses the non-pre-release version which isn't compatible with the pre-release version I selected of the main AI package. Thanks,
