### ISSUE TITLE
Error "Value is required to set custom dimension. Key: Kubernetes.ReplicaSet.Name"

### ISSUE THREAD

**Issue by sarthakmahapatra** [Microsoft/ApplicationInsights-Kubernetes#145]
Hi 

I upgraded Microsoft.ApplicationInsights.Kubernetes from 1.0.0-beta1 to 1.0.0. Started getting this error

``` c#
fail: Microsoft.ApplicationInsights.Kubernetes.KubernetesTelemetryInitializer[0]
      Value is required to set custom dimension. Key: Kubernetes.ReplicaSet.Name
```

this pod is running as a DeamonSet.

**Comment by xiaomi7732** [comment]
@sarthakmahapatra Thanks for reporting the issue. DeamonSet is an interesting scenario. I'll take a look and then gets back to you.

**Comment by sarthakmahapatra** [comment]
@xiaomi7732 thanks, looking forward to your response.

**Comment by xiaomi7732** [comment]
@sarthakmahapatra The error is logged for debugging purpose. Although, I think should **not** be recorded as an error.
The PR will make the property optional so that the error message will only be seen in the debugging logging.

**Comment by sarthakmahapatra** [comment]
Looks good, thanks
