### ISSUE TITLE
The mehtod name of EnableKubernetes() is misleading

### ISSUE THREAD

**Issue by Expecho** [Microsoft/ApplicationInsights-Kubernetes#148]
Although I love this addon I am not that fond of the naming given this piece of code:

    public void ConfigureServices(IServiceCollection services)
    {
        services.EnableKubernetes();  // Add this line of code
        ...
    }

We are not enabling kubernetes here, we are enabling the enrichment of AI telemetry. When reading the code it is not clear at all what it does exactly. 

I propose an other name like `AddKubernetesAITelemetryEnricher`  or something similair.

**Comment by xiaomi7732** [comment]
Thanks for the feedback. Point taken. We will update the name and deprecate the existing method.
