### ISSUE TITLE
Pod name requirement means extension doesn't "just work" on Windows

### ISSUE THREAD

**Issue by davidmatson** [microsoft/ApplicationInsights-Kubernetes#172]
Related to #171, unlike on Linux, at least one extra configuration step is required to get the extension working. This issue tracks making things "just work" on Windows like they do on Linux. Likely that requires driving changes upstream to make the pod name accessible from within the pod - where would we need to get assistance to make this work end-to-end?

**Comment by xiaomi7732** [comment]
That is right.
In the Linux implementation, the pod name is parsed from the cgroup, which doesn't exist in the Windows world.
If anyone knows how to get the container id / pod info somehow from within a Windows container, I'll be glad to update the implementation to eliminate the step.

**Comment by davidmatson** [comment]
Should we try asking the Kubernetes folks? https://github.com/kubernetes/kubernetes

**Comment by davidmatson** [comment]
We tested and found that it is possible to get the host name on Windows from within the pod without using the downward API. Hostname.exe from within the pod works, which internally uses this Win32 API:
https://docs.microsoft.com/en-us/windows/desktop/api/winsock/nf-winsock-gethostname

Could this extension be updated to use this API on windows to have the pod name "just work" there too?

**Comment by xiaomi7732** [comment]
@davidmatson Thanks for the info.
By reading the document for getHostName(), it returns the host name of the container, right? (like machine name or machine name in a domain)

I have difficulties to use that to correlate back to the container id or use that to figure out the pod name. **Could you please explain in detail how is that going to work**?

**Comment by davidmatson** [comment]
Inside a container, this API returns the pod name. Try doing something like this:
kubectl exec <pod> hostname.exe
and compare it with
kubectl exec <pod> cmd /c echo %COMPUTERNAME%

**Comment by xiaomi7732** [comment]
@davidmatson thanks for the quick turnaround. I'll take a look at it.

**Comment by xiaomi7732** [comment]
@davidmatson Followed the lead, here's what I see:
```shell
saars@Saars-p51:~$ kubectl exec -it nanoserver-iis-5d999b87d7-mtz6w hostname.exe
c003088533e3
```
**c003088533e3** is the computer / host name, which agrees with the API spec.

**However**, it is neither the pod name nor can I correlate it back to the **pod name** (nanoserver-iis-5d999b87d7-mtz6w), what do I miss here?
```shell
saars@Saars-p51:~$ kubectl describe pod nanoserver-iis-5d999b87d7-mtz6w
Name:               nanoserver-iis-5d999b87d7-mtz6w
Namespace:          default
...
Labels:             app=nanoserver-iis
                    pod-template-hash=5d999b87d7
Status:             Running
Controlled By:      ReplicaSet/nanoserver-iis-5d999b87d7
Containers:
  nanoserver-iis:
    Container ID:   aci://ce0305f57fa146ec8c549669a3a8e0978472af1186d9faa79501c0687b34a473
    Image:          microsoft/iis:nanoserver
    Image ID:
    Port:           80/TCP
    State:          Running
      Started:      Sun, 28 Apr 2019 17:49:08 -0700
    Ready:          True
    Restart Count:  0
...
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-2v2xf (ro)
...
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  2m    default-scheduler  Successfully assigned default/nanoserver-iis-5d999b87d7-mtz6w to virtual-kubelet-virtual-kubelet-windows-westus2
```

**Comment by davidmatson** [comment]
The behavior may be different on older base images. If you use the following base image, do you see the same output I was seeing?
mcr.microsoft.com/windows/servercore:1809

**Comment by xiaomi7732** [comment]
@davidmatson I currently don't have a good K8s cluster to host servercore:1809/nanoserver:1809. That said, the assumption is the API wasn't return the expected value until recently. That leads to branch cases. I think it is easier to keep using downward API until it stabilized. Idea?

**Comment by davidmatson** [comment]
1809 is now the current Long Term Servicing Branch. I think it would be great if this extension "just works" on the latest stable version and only requires using the downward API on older versions.

I think the code could do something like get the hostname via an API unless one is provided via an environment variable - adding a single "if" statement so things just work going forward seems worthwhile, IMO.

**Comment by xiaomi7732** [comment]
Manual Pod name is not required anymore as long as the hostname returns correct pod name.
Fix released: https://www.nuget.org/packages/Microsoft.ApplicationInsights.Kubernetes/2.0.4
