### ISSUE TITLE
ZeroCodeLightUp + Configuration from Azure KeyVault

### ISSUE THREAD

**Issue by ferantivero** [microsoft/ApplicationInsights-Kubernetes#175]
I've been trying to implement the ZeroCodeLigthUp approach without APPINSIGHTS_INSTRUMENTATIONKEY env var but setting such key value in Configuration["ApplicationInsights:InstrumentationKey"] without luck. The latter is a valid custom configuration provider in [ApplicationInsights-aspnetcore](https://github.com/Microsoft/ApplicationInsights-aspnetcore/wiki/Custom-Configuration#configuration-based-approach) by invoking:

```services.AddApplicationInsightsTelemetry(Configuration);```

Scenario: KeyVault to Configuration + ZeroCodeLightUp.

Am I missing something?

**Comment by xiaomi7732** [comment]
Hi @ferantivero, there are 2 key settings to light up Application Insights for Kubernetes, one is **Application Insights instrumentation key**; The second is the environment variable of **ASPNETCORE_HOSTINGSTARTUPASSEMBLIES** to Microsoft.ApplicationInsights.Kubernetes.HostingStartup.

* Do you check the two configuration set up correctly?

* When you are not seeing it work, what's the behavior? Does it not sending any data to your application insights resource? Or the data doens't include all the properties that you expected?

If you'd like to share your project, I can help take a look at the configuratoins.

**Comment by ferantivero** [comment]
thanks for your reply @xiaomi7732, I'm aware of those 2 key settings that are required and  when I setup both everything works as expected. But please note that I do not want to expose the IKey from an Environment Variable (first key setting required) but use KeyVault instead.

**Comment by xiaomi7732** [comment]
@ferantivero Thanks for the reply. Are you deploying the application as Azure Website? Have you ever looked into using the app settings blade in the portal to set the iKey? Or is there any requirement that you have to use KeyVault?

**Comment by ferantivero** [comment]
@xiaomi7732 been off for a while here 🙂 

yes, for security reasons we do want to use KeyVault and not get iKey exposed through Environment Variables.

**Comment by xiaomi7732** [comment]
@ferantivero This a general topic about securing instrumentation key in KeyVault and I think this issue is addressed here: https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/535. Please take a look and see if that solves your problem.

**Comment by xiaomi7732** [comment]
Thanks @ferantivero for the contribution.
Please upgrade to the latest release:
https://www.nuget.org/packages/Microsoft.ApplicationInsights.Kubernetes/1.1.0
