### ISSUE TITLE
Enabling k8s support in a .Net Core app fails

### ISSUE THREAD

**Issue by brobichaud** [microsoft/ApplicationInsights-Kubernetes#177]
I'm trying to enable k8s support in my .Net Core app following the steps [here](https://github.com/Microsoft/ApplicationInsights-Kubernetes/wiki/Getting-Started-for-.NET-Core-Applications) and am having trouble.

It says to include the AspNetCore nuget, which I'm guessing is a copy/paste error from the equiv page for enabling it in AspNet apps? But even if I add that and the ApplicationInsights.Kubernetes nuget there is no EnableKubernetes() method to call. Clearly I'm doing something grossly wrong here. Note this is a Windows container, if that's relevant.

 Thoughts?

**Comment by xiaomi7732** [comment]
@brobichaud Sorry for the confusion. Please follow the example of this for apps in Windows container: https://github.com/Microsoft/ApplicationInsights-Kubernetes/tree/develop/examples/WindowsContainer.

**Comment by brobichaud** [comment]
But I am trying to enable it in a DotNet Core app, not an AspNet Core app. That link seems biased to AspNet Core.

**Comment by xiaomi7732** [comment]
@brobichaud Please follow the Windows Container example above, but try using the following code to inject AI.K8s.
// I am sorry but I have limited internet access now that I can't verify it. Please post back if there's more problem:

```csharp
        static int Main(string[] args)
        {
            // Adding all environment variables into IConfiguration
            IConfiguration config = new ConfigurationBuilder().AddEnvironmentVariables().Build();

            // Read instrumentation key from IConfiguration
            string iKey = config["APPINSIGHTS_INSTRUMENTATIONKEY"];
            // Making sure ApplicationInsights instrumentation key is set
            if (string.IsNullOrEmpty(iKey))
            {
                Console.WriteLine("Please set the environment variable of APPINSIGHTS_INSTRUMENTATIONKEY with a property instrumentation key.");
                return -1;
            }

            // Build the client using the iKey to send trace.
            using (TelemetryConfiguration configuration = new TelemetryConfiguration(iKey))
            {
                configuration.AddApplicationInsightsKubernetesEnricher(applyOptions: null);

                TelemetryClient client = new TelemetryClient(configuration);
                while (true)
                {
                    // Send the trace
                    client.TrackTrace("Hello from AI SDK");
                    client.Flush();
                    Thread.Sleep(30000);
                }
            }
        }
```

**Comment by ferantivero** [comment]
@xiaomi7732 in my case scenario I've been able to get it working and also getting auto-track dependencies (e2e transaction), but I'm facing the following issues:

1. although it adds initializer, the enricher is not working: telemetry is not being contextualized with k8s metadata like container name, image name, etc. 
2. incorrect cloud role name from Application Maps and e2e transaction
3. live stream not showing any activity

Point 3 is more applicationinsights-aspnetcore package related, but wanted to mention just in case you faced a similar behavior. Perhaps I should add some extra initializer, not sure.

**Comment by xiaomi7732** [comment]
@ferantivero I believe you have figured this out based on the comment in #173, does that sound right?

**Comment by ferantivero** [comment]
@xiaomi7732 the issue I'm detailing here is about having feature parity between Web Host and Generic Host. This could be partially tackled from #178 (docs/samples). But it's definitely upstream too as far as I understand.

#173 is just about using Microsoft.Extensions.Logging.Application 2.9.1 with Microsoft.ApplicationInsights.Kubernetes 1.0.2 (lib incompatility issue).

**Comment by xiaomi7732** [comment]
The way moving forward will be to use ApplicationInsights.ILogger provider. See #185 for details.

**Comment by xiaomi7732** [comment]
Address this issue with #184 ; The documentation is updated with #185; The final bits will take a few days to be released.
Take a peek here: https://github.com/microsoft/ApplicationInsights-Kubernetes/tree/develop/examples/BasicConsoleAppILogger

**Comment by xiaomi7732** [comment]
For the latest implementation, please upgrade to the latest release:
https://www.nuget.org/packages/Microsoft.ApplicationInsights.Kubernetes/1.1.0
