### ISSUE TITLE
403 Error for Kubernetes Telemetry

### ISSUE THREAD

**Issue by bdschaap** [microsoft/ApplicationInsights-Kubernetes#179]
I configured an AKS cluster, added the App Insights Kubernetes nuget package to a test project, and have deployed the application with Azure Dev Spaces using Visual Studio.  However, the first message repeats in my debug window in Visual Studio several dozen times about every half second apart.  The subsequent messages appear after that.  However, I am able to get it to work in a K8s cluster within Docker Desktop.

Application Insights Telemetry: {"name":"Microsoft.ApplicationInsights.Dev.346f28014b2f4f5a836bae11ac1ca23b.RemoteDependency","time":"2019-03-11T22:07:15.6205953Z","iKey":"...","tags":{"ai.internal.sdkVersion":"ai-k8s:1.0.2.65534","ai.operation.id":"76c9c780-43f202492306670c","ai.application.ver":"1.0.0.0"},"data":{"baseType":"RemoteDependencyData","baseData":{"ver":2,"name":"GET /api/v1/namespaces/default/pods","id":"|76c9c780-43f202492306670c.","data":"https://aks1-rg-aks1-c3bf24-xxxxxxxx.hcp.eastus.azmk8s.io/api/v1/namespaces/default/pods","duration":"00:00:00.0114764","resultCode":"403","success":false,"type":"Http","target":"aks1-rg-aks1-c3bf24-xxxxxxxx.hcp.eastus.azmk8s.io","properties":{"AspNetCoreEnvironment":"Development","DeveloperMode":"true"}}}}

[41m[1m[37mcrit[39m[22m[49m: Microsoft.ApplicationInsights.Kubernetes.K8sEnvironmentFactory[0]
      Fail to fetch the pod information in time. Kubernetes info will not be available for the telemetry.
Microsoft.ApplicationInsights.Kubernetes.K8sEnvironmentFactory:Critical: Fail to fetch the pod information in time. Kubernetes info will not be available for the telemetry.

**Comment by xiaomi7732** [comment]
@bdschaap AKS cluster enables RBAC by default. Do you have the service account setup? Please reference [Setup the default Service Account for RBAC enabled cluster](https://github.com/Microsoft/ApplicationInsights-Kubernetes/tree/develop/examples/BasicUsage_clr21_RBAC#setup-the-default-service-account-for-rbac-enabled-cluster).

**Comment by xiaomi7732** [comment]
Close this there's no response for a while. Feel free to open new issue if more info comes up.

**Comment by bdschaap** [comment]
Apologies for the delay.  This worked and thanks for the guidance.

**Comment by xiaomi7732** [comment]
@bdschaap Thanks for your confirmation!

**Comment by bvrabete** [comment]
Hi there,

I am still seeing this error despite following the steps for defining the service account. Where should I be looking to debug the issue? What am I missing?

See below the log entries:

2020-08-05T08:00:57.799570616Z crit: Microsoft.ApplicationInsights.Kubernetes.K8sEnvironmentFactory[0]
2020-08-05T08:00:57.799638993Z       Fail to fetch the pod information in time. Kubernetes info will not be available for the telemetry.
2020-08-05T08:00:57.820673304Z fail: Microsoft.ApplicationInsights.Kubernetes.KubernetesTelemetryInitializer[0]
2020-08-05T08:00:57.820726047Z       Query Kubernetes Environment timeout.
2020-08-05T08:00:57.821135753Z fail: Microsoft.ApplicationInsights.Kubernetes.KubernetesTelemetryInitializer[0]
2020-08-05T08:00:57.821149252Z       Query Kubernetes Environment timeout.
2020-08-05T08:00:57.841309111Z crit: Microsoft.ApplicationInsights.Kubernetes.K8sEnvironmentFactory[0]
2020-08-05T08:00:57.841328763Z       Fail to fetch the pod information in time. Kubernetes info will not be available for the telemetry.

**Comment by xiaomi7732** [comment]
Hi @bvrabete  It seems like the enricher can't reach the proxy. Could you please turn on the diagnostics and run it again:
https://github.com/microsoft/ApplicationInsights-Kubernetes/blob/develop/docs/SelfDiagnostics.MD
It will generate detailed logs around what is happening.

If you want, post the logs here and I can help take a look what is going on.

**Comment by xiaomi7732** [comment]
Close due to not actionable.
