### ISSUE TITLE
BasicConsoleAppILogger exemple not working

### ISSUE THREAD

**Issue by laulaua3** [microsoft/ApplicationInsights-Kubernetes#187]
Hello,
I try your exemple but I have no information of K8s in Application Insight:

2019-07-04T14:13:31.438 | Logger is working | 1 | trace | {"CategoryName":"XXXXX.Template.Program","{OriginalFormat}":"Logger is working","Method":"Main"} |   |   |   | PC | 0.0.0.0 | Dublin | Leinster | Ireland | testk8slog-7b66f99d6f-gxmrp.(none) | 69a7b2ed-4658-499f-acac-b24e670fcda5 | job-aks-app-insights | dbdffd18-4f83-4185-b480-c504e4309e86 | ai-k8s:1.1.0.0 | 23799490-9e55-11e9-b995-813b3150a92e | 1 |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
  | timestamp [UTC]2019-07-04T12:13:31.438995ZmessageLogger is workingseverityLevel1itemTypetracecustomDimensions{"CategoryName":"XXXX.Template.Program","{OriginalFormat}":"Logger is working","Method":"Main"}client_TypePCclient_IP0.0.0.0client_CityDublinclient_StateOrProvinceLeinsterclient_CountryOrRegionIrelandcloud_RoleInstancetestk8slog-7b66f99d6f-gxmrp.(none)appId69a7b2ed-4658-499f-acac-b24e670fcda5appNamejob-aks-app-insightsiKeydbdffd18-4f83-4185-b480-c504e4309e86sdkVersionai-k8s:1.1.0.0itemId23799490-9e55-11e9-b995-813b3150a92eitemCount1 |   | timestamp [UTC] | 2019-07-04T12:13:31.438995Z |   | message | Logger is working |   | severityLevel | 1 |   | itemType | trace |   | customDimensions | {"CategoryName":"XXX.Template.Program","{OriginalFormat}":"Logger is working","Method":"Main"} |   | client_Type | PC |   | client_IP | 0.0.0.0 |   | client_City | Dublin |   | client_StateOrProvince | Leinster |   | client_CountryOrRegion | Ireland |   | cloud_RoleInstance | testk8slog-7b66f99d6f-gxmrp.(none) |   | appId | 69a7b2ed-4658-499f-acac-b24e670fcda5 |   | appName | job-aks-app-insights |   | iKey | dbdffd18-4f83-4185-b480-c504e4309e86 |   | sdkVersion | ai-k8s:1.1.0.0 |   | itemId | 23799490-9e55-11e9-b995-813b3150a92e |   | itemCount | 1
  | timestamp [UTC] | 2019-07-04T12:13:31.438995Z
  | message | Logger is working
  | severityLevel | 1
  | itemType | trace
  | customDimensions | {"CategoryName":"XXX.Template.Program","{OriginalFormat}":"Logger is working","Method":"Main"}
  | client_Type | PC
  | client_IP | 0.0.0.0
  | client_City | Dublin
  | client_StateOrProvince | Leinster
  | client_CountryOrRegion | Ireland
  | cloud_RoleInstance | testk8slog-7b66f99d6f-gxmrp.(none)
  | appId | 69a7b2ed-4658-499f-acac-b24e670fcda5
  | appName | job-aks-app-insights
  | iKey | dbdffd18-4f83-4185-b480-c504e4309e86
  | sdkVersion | ai-k8s:1.1.0.0
  | itemId | 23799490-9e55-11e9-b995-813b3150a92e
  | itemCount | 1

When i active the trace log of ApplicationInsightsKubernetes I see this message:
[Information] KubernetesTelemetryInitializer is injected.
[Trace] **Application Insights for Kubernetes telemetry initializer is used but the content has not ready yet**.
And if i make more log, this message appears before each log.
When the app in ended we have :
[Debug] Application Insights for Kubernetes environment initialized.
Any idea ?
Thx.

**Comment by xiaomi7732** [comment]
@laulaua3 I'll take a look.

**Comment by xiaomi7732** [comment]
@laulaua3 Thanks for the feedback. There is a mistake in the example, the enablement of AI.K8s happens too late - later than configure telemetry configuration.

Please refer to the PR #188 for the fix. Primarily, pull the line of enable Application Insights Kubernetes Enricher to above `services.Configure<TelemetryConfiguration>`.

Here's how the logs look like
```bash
[Trace] Application Insights for Kubernetes telemetry initializer is invoked.
[Trace] Finish telemetry initializer.
info: BasicILoggerConsole.Program[0]
      Logger is working
[Trace] Application Insights for Kubernetes telemetry initializer is invoked.
[Trace] Finish telemetry initializer.
info: BasicILoggerConsole.Program[0]
      Logger is working
```

And here's how it look like in application insights:
![image](https://user-images.githubusercontent.com/3674549/60943183-fbd13a80-a299-11e9-838f-593cb9af3c0c.png)

Please let us know if that works for you or not.

**Comment by laulaua3** [comment]
@xiaomi7732 Thanks for your reply,
I've tested but always the same problem, the only different is i'm on AKS not on an K8s Local.
this is my code

```CSHARP
static async Task<int> Main(string[] args)
 {
            int result = -1;// Fail by default.
            var channel = new InMemoryChannel();
            IConfiguration configuration = Configurator.GetConfiguration();
            var serviceProvider = await DependencyInjector.ConfigureServices(configuration, channel);

            ILogger<Program> logger =  serviceProvider.GetRequiredService<ILogger<Program>>();
            logger.LogInformation("Application start.");

            try
            {
             // Code.
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Application failed");
                result = -1;
            }
            finally
            {
                logger.LogInformation("Application end.");
                logger.LogInformation($"Exit status code : {result}");
                channel.Flush();
            }
            return result;
 }
```
For DependencyInjector.ConfigureServices

 ```CSHARP
public static Task<IServiceProvider> ConfigureServices(IConfiguration configuration, ITelemetryChannel telemetry)
{
            var services = new ServiceCollection();

            ConfigureLogger(configuration, telemetry, services);

            return Task.FromResult<IServiceProvider>(services.BuildServiceProvider());
 }

private static void ConfigureLogger(IConfiguration configuration, ITelemetryChannel telemetry, ServiceCollection services)
 {

            LogLevel logLevel = LogLevel.Trace;
             //var observer = new ApplicationInsightsKubernetesDiagnosticObserver(DiagnosticLogLevel.Trace);
             //ApplicationInsightsKubernetesDiagnosticSource.Instance.Observable.SubscribeWithAdapter(observer);
            services.AddApplicationInsightsKubernetesEnricher();
            // For logger (ApplicationInsights).
            services.Configure<TelemetryConfiguration>(
                           (config) =>
                           {
                               config.TelemetryChannel = telemetry;

                               var environmentName = Environment.GetEnvironmentVariable("CORE_ENVIRONMENT");
                               config.TelemetryInitializers.Add(new JobTelemetryInitializer(environmentName));

                           });
            services.AddLogging(builder =>
            {
                builder.AddFilter<ApplicationInsightsLoggerProvider>("", logLevel);

                builder.AddApplicationInsights(configuration.GetSection("ApplicationInsights").Get<string>("InstrumentationKey"));
                builder.AddConsoleAdvanced(configuration.GetSection("Logging"));
            });
           
            services.Configure<LoggerFilterOptions>(options => options.MinLevel = logLevel);
}         
```
JobTelemetryInitializer :
 ```CSHARP
public sealed class JobTelemetryInitializer : ITelemetryInitializer
{

        private readonly string environment;

        public JobTelemetryInitializer(string environment)
        {
            this.environment = environment;
        }
        public void Initialize(ITelemetry telemetry)
        {
            if (telemetry is ISupportProperties telemetryProps)
            {
                telemetryProps.Properties.Add("Environment", environment);
            }
        }
}
```
Thx

**Comment by xiaomi7732** [comment]
@laulaua3 Thanks for the detailed info. Do you know do you have RBAC enabled (it is enabled by default in AKS)? If yes, did you have the correct account binding? Please refer to [here](https://github.com/microsoft/ApplicationInsights-Kubernetes/tree/develop/examples/BasicUsage_clr21_RBAC#setup-the-default-service-account-for-rbac-enabled-cluster) for how to do it.

**Comment by laulaua3** [comment]
@xiaomi7732 Ok, I had already done (only saRole.yaml)
![image](https://user-images.githubusercontent.com/8473051/61038531-79499780-a3cd-11e9-8281-1afd10fc5e9d.png)
And the log of the pod (I did removed critical information)
```
[Information] KubernetesTelemetryInitializer is injected.
[Trace] Application Insights for Kubernetes telemetry initializer is used but the content has not ready yet.
[20190711-11:19:55] info: Darwin.Aks.Job.Template.Program[0]
      Application start.
[Trace] Not a authority signed certificate.
[Trace] Server Cert RAW:  XXXXX
[Trace] Building certificate chain.
[Trace] Client Cert RAW:  XXXXXX
[Trace] Is Chain successfully built: True
[Trace] Application Insights for Kubernetes telemetry initializer is used but the content has not ready yet.
[20190711-11:19:55] info: Darwin.Aks.Job.Template.Program[0]
      Current Arguments: -v False
[Trace] Application Insights for Kubernetes telemetry initializer is used but the content has not ready yet.
[20190711-11:19:55] info: Darwin.Aks.Job.Template.Program[0]
      Quick Start Example!
[Trace] Application Insights for Kubernetes telemetry initializer is used but the content has not ready yet.
[20190711-11:19:55] info: Darwin.Aks.Job.Template.Program[0]
      Application end.
[Trace] Application Insights for Kubernetes telemetry initializer is used but the content has not ready yet.
[20190711-11:19:55] info: Darwin.Aks.Job.Template.Program[0]
      Exit status code : 0
[Debug] Query succeeded.
[Debug] K8s info avaialbe in: 490 ms.
[Trace] Default Header: Authorization: Bearer XXXXX
 [Debug] Query succeeded.
[Debug] K8s info avaialbe in: 7 ms.
[Debug] Getting container status of container-id: 86ae1760ea2156769ddd499f7c00534c22c054b0d7fd99d3d514ffe3f8c23d8d
[Trace] Default Header: Authorization: Bearer XXXXX
 [Debug] Query succeeded.
[Trace] Default Header: Authorization: Bearer XXXXX
 [Debug] Query succeeded.
[Trace] Default Header: Authorization: Bearer XXXXXX
 [Debug] Query succeeded.
[Debug] Application Insights for Kubernetes environment initialized.
```

**Comment by xiaomi7732** [comment]
@laulaua3 Thanks for sending the logs. By reading the log and simulating the code you sent, I see that the initialization happens after the log that you invoked.

The way AI.K8s works is that it will query the K8s cluster master for the pod information, that happens asynchronously with the other logic - your code, in this case.

And when the time the initialization finished, your code has already finish running.

I updated the code you shared a bit to make it sending the logs every 5 seconds like this:
```csharp
...
            try
            {
                while(true)
                {
                    logger.LogInformation("Logger is invoked.");
                    await Task.Delay(TimeSpan.FromSeconds(5));
                }
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Application failed");
                result = -1;
            }
            finally
            {
                logger.LogInformation("Application end.");
                logger.LogInformation($"Exit status code : {result}");
                channel.Flush();
            }
            return result;
```
And I got this log.
```shell
[Debug] Application Insights Kubernetes injected the service successfully.
[Debug] Kubernetes base address: https://10.96.0.1:443/
[Debug] Initialize Application Insights for Kubernetes telemetry initializer with Options:
{"InitializationTimeout":"00:02:00"}
[Trace] Creating KubeHttpClient
[Debug] Access token is not null. Set default request header.
[Trace] Creating K8sQueryClient
[Trace] Default Header: Authorization: Bearer ...
[Trace] KubernetesTelemetryInitializer has been injected into telemetry configuration #16495015.
[Information] KubernetesTelemetryInitializer is injected.
[Trace] Application Insights for Kubernetes telemetry initializer is used but the content has not ready yet.
[Trace] Application Insights for Kubernetes telemetry initializer is used but the content has not ready yet.
info: ConsoleAppInvestigate.Program[0]
      Application start.
info: ConsoleAppInvestigate.Program[0]
      Logger is invoked.
[Trace] Not a authority signed certificate.
[Trace] Server Cert RAW:
[Trace] Building certificate chain.
[Trace] Client Cert RAW:
[Trace] Is Chain successfully built: True
[Debug] Query succeeded.
[Debug] K8s info avaialbe in: 519 ms.
[Trace] Default Header: Authorization: Bearer 
[Debug] Query succeeded.
[Debug] K8s info avaialbe in: 5 ms.
[Debug] Getting container status of container-id: 62f3220a70634a900f2f80fe85d
[Trace] Default Header: Authorization: Bearer 
[Debug] Query succeeded.
[Trace] Default Header: Authorization: Bearer 
[Debug] Query succeeded.
[Trace] Default Header: Authorization: Bearer ...

[Debug] Query succeeded.
[Debug] Application Insights for Kubernetes environment initialized.
[Trace] Application Insights for Kubernetes telemetry initializer is invoked.
[Trace] Finish telemetry initializer.
info: ConsoleAppInvestigate.Program[0]
      Logger is invoked.
[Trace] Application Insights for Kubernetes telemetry initializer is invoked.
[Trace] Finish telemetry initializer.
info: ConsoleAppInvestigate.Program[0]
      Logger is invoked.
...
```
In the log, the very first 2 logs are not having any kubernetes information because the data is not ready yet. That's what you have been seeing.
Starting from the 3rd request, invoked 5 seconds later, should have the information.

I attached a copy of the implementations just as FYI:
[Investigate.zip](https://github.com/microsoft/ApplicationInsights-Kubernetes/files/3383981/Investigate.zip)

Try put a 1 second delay before the logic that you are interested:
```csharp
            await Task.Delay(TimeSpan.FromSeconds(1));
            try
            {
                // your code
            }
            catch (Exception ex)
            ...
```

One thing that I have been curious is: what is your application do? Why is it a short lived app in the container? What is the scenario?

Anyway, give it a short and let us know!

**Comment by laulaua3** [comment]
@xiaomi7732 ok , that is what I thought, i will test your solution, and to anwser your question it 's not a real application but a template to start a application for the developper in internal.
Would passing the AddApplicationInsightsKubernetesEnricher  method asynchronously not solve the problem ?

**Comment by laulaua3** [comment]
@xiaomi7732After testing and some investigation, I found the problem.
In ctor  of the class KubernetesTelemetryInitializer,there is a call to the SetK8sEnvironment method that is not synchronous.
 `_ = SetK8sEnvironment();`
If I set it synchronously 
`SetK8sEnvironment (). Wait();`
 the initialization is done properly before continuing.
I don't know there a impact if i make that for the Webapi
Thx

**Comment by xiaomi7732** [comment]
laulaua3 Thanks for digging into the issue. That is by design. The reason is to reduce impact on the real code as much as possible.
Basically, for the first few requests, it is possible that the kubernetes info is not attached; But your application is still up and running and there's still telemetry by application insights.

Please file another issue if you really want the synchronous mode and we will look into ways to implement it. There's something we might be able to do:
* One of the quick solution would be for us to emit an event when the info is ready.
* We might also be able to take a delegate/Action/lambda on the configuration so that you can hook your code there.

I think we pretty much reached the bottom of this investigation. I'll leave this issue open for a few days for further discussion. Then I'll close it.

**Comment by laulaua3** [comment]
@xiaomi7732 I'm agree with you for this design but not working in console app and AKS (my case). I do not think adding a task.delay is a good choice (the waiting time will be very random) . 
I close the issue.

**Comment by xiaomi7732** [comment]
@laulaua3 Thanks for your input!
