### ISSUE TITLE
appName shown as name of application insights

### ISSUE THREAD

**Issue by hisuwh** [microsoft/ApplicationInsights-Kubernetes#197]
Thanks to this package I can now see my kubernetes applications on the application map.  However the appName property is set to the name of the application insights instance for all of them and hence they all show as one node on the map.

This obviously isn't very helpful.  I realise this may not be an issue with this package directly but the documentation is sparse on this subject so I was hoping someone here might be able to help me.

**Comment by xiaomi7732** [comment]
Hey, you are right, app name is not manipulated by this package. If I understand correct, you have shared iKey in multiple applications, right? I don't think that is recommended by application insights. @OsvaldoRosado could you please suggest on that?

**Comment by OsvaldoRosado** [comment]
@SoubhagyaDash should be able to help with the guidance for this

**Comment by SoubhagyaDash** [comment]
We recommend a different AI resource for every independently deployable application component. You can use either model however, single or multiple AI resources – it does *NOT* affect Application Map or the Transaction Diagnostics experiences. 
 
Each AI resource comes with metrics that are available out of the box, and are aggregations on the telemetry reported to it. If completely separate components report to the same AI resource, these metrics may not make sense to dashboard/alert on.
 
Use single AI resource:
•	For application components that are deployed together. Usually developed by a single team, managed by the same set of DevOps/ITOps users.
•	If it makes sense to aggregate KPIs such as response durations, failure rates in dashboard etc., across all of them by default (you can choose to segment by role name in the Metrics Explorer experience).
•	If there is no need to manage RBAC differently between the application components.
•	If you don’t need metrics alert criteria that are different between the components.
•	If you do not need to manage continuous exports differently between the components.
•	If you do not need to manage billing/quotas differently between the components.
•	If it is okay to have an API key have the same access to data from all components. And 10 API keys are sufficient for the needs across all of them.
•	If it is okay to have the same smart detection and work item integration settings across all roles.
 
Other things to keep in mind:
•	You may need to add custom code to ensure that meaningful values are set into the “Cloud_RoleName” attribute. Without meaningful values set for this attribute, *NONE* of the portal experiences will work.
o	For Service Fabric applications and classic cloud services, the SDK automatically reads from the Azure Role Environment and sets these. For all other types of apps, you will likely need to set this explicitly.
•	Live Metrics experience does not support splitting by role name.

**Comment by hisuwh** [comment]
@SoubhagyaDash 
Thanks for the information.  I think an AI resource per deployment won't work very well for us as we would have many to manage.  Its also helpful to trace a request across microservices from one instance.

I think the Cloud_RoleName part is what I need.  Any guidance on how I can set this? Is it just an environment variable or is there more to it than that?

**Comment by xiaomi7732** [comment]
@hisuwh Hey, could you please check out what's the value in your telemetry for 'cloud_RoleName'?
When the enricher is on, you shall have roleName set to the container name:
https://github.com/microsoft/ApplicationInsights-Kubernetes/blob/822f927940899f6d629c76cd6b2ac619ab9eea01/src/ApplicationInsights.Kubernetes/TelemetryInitializers/KubernetesTelemetryInitializer.cs#L73

Copied code:
```csharp
                    // Setting the container name to role name
                    if (string.IsNullOrEmpty(telemetry.Context.Cloud.RoleName))
                    {
                        telemetry.Context.Cloud.RoleName = k8sEnv.ContainerName;
                    }
```

**Comment by hisuwh** [comment]
@xiaomi7732 Thanks.
I can see that my role name is set correctly now and my applications are showing up correctly on the application map as well.

Think this is related to #199 and the fact I didn't have this working correctly.  Thanks for your help.

**Comment by xiaomi7732** [comment]
@hisuwh Thank you for the update.
