### ISSUE TITLE
Two sets of instructions for enabling self diagnositics - which is right?

### ISSUE THREAD

**Issue by hisuwh** [microsoft/ApplicationInsights-Kubernetes#198]
There are two sets of instructions for enabling self diagnostics:
- [here](https://github.com/Microsoft/ApplicationInsights-Kubernetes/wiki/%5BAdvanced%5D-How-to-enable-self-diagnostics-for-ApplicationInsights.Kubernetes)
- [and here](https://github.com/microsoft/ApplicationInsights-Kubernetes/blob/develop/docs/SelfDiagnostics.MD)

Which is the most correct/up-to-date?

**Comment by xiaomi7732** [comment]
Hi @hisuwh, thanks for noticing the issue.
The later is up to date: https://github.com/microsoft/ApplicationInsights-Kubernetes/blob/develop/docs/SelfDiagnostics.MD
I'll remove the old post.
