### ISSUE TITLE
Add k8s namespace name to the enricher

### ISSUE THREAD

**Issue by skwasiborski** [microsoft/ApplicationInsights-Kubernetes#201]
Currently namespace name is not by the enricher to the context. Namespace is important info especially during development or in multi-tenant setups when multiple versions of the same deployment are deployed to different namespaces. The namespace name can be fund in the following file:
`/var/run/secrets/kubernetes.io/serviceaccount/namespace` so extracting it should not be an issue.

**Comment by karolz-ms** [comment]
+1 on this ask. Separating deployments by namespace is a very common K8s practice and having namespace name in the context adds a lot of value.

**Comment by xiaomi7732** [comment]
Fix available by #205

**Comment by xiaomi7732** [comment]
Fixed in [1.1.2](https://www.nuget.org/packages/Microsoft.ApplicationInsights.Kubernetes/1.1.2).
