### ISSUE TITLE
The API path has been changed after k8s v1.16

### ISSUE THREAD

**Issue by hermanho** [microsoft/ApplicationInsights-Kubernetes#203]
The API path has been changed so the information of deployment and replicaset are empty.

Reference:
https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

**Comment by xiaomi7732** [comment]
@hermanho, thanks for the heads up. I'll update related code.

**Comment by xiaomi7732** [comment]
Released  in [1.1.2](https://www.nuget.org/packages/Microsoft.ApplicationInsights.Kubernetes/1.1.2).
