### ISSUE TITLE
Kubernetes Cluster Name not getting logged

### ISSUE THREAD

**Issue by dewanymca** [microsoft/ApplicationInsights-Kubernetes#204]
We are running active-active configuration for Kubernetes cluster for different environment. We are unable to see clustername getting logged as part of telemetry. This will help us in identitfying which cluster has processed the request and how load balancing is happening. Is there anything we are missing here? How to enable ClusterName.

**Comment by xiaomi7732** [comment]
@dewanymca Could you please clarify what is the cluster name you are looking for to record? Could you please describe how are you getting it? For example, what kind of kubectl cmd or what UI. A screenshot of where you get it manually will be really helpful for us to understand what is the data point you are trying to record. Thanks.

**Comment by dewanymca** [comment]
When we run command kubectl config get-contexts we recieve clustername as output in one of the column, we are looking to get smae in Applicaiton insight

**Comment by xiaomi7732** [comment]
@dewanymca For now, apparently, there's no way to get the cluster name from within the cluster.
References:
* https://github.com/doriordan/skuber/issues/238
* https://github.com/kubernetes/kubernetes/issues/44954

There's a draft for standardize the cluster name:
* https://docs.google.com/document/d/1F__vEKeI41P7PPUCMM9PVPYY34pyrvQI5rbTJVnS5c4/edit#heading=h.4igbcpajqich

Is it possible:
* for you to have 2 different instrumentation keys, one per cluster to separate the data?
* for you to aggregate data from other IDs that is recorded, like a node id or so?

**Comment by raelga** [comment]
+1 

Some time when you need to manage cloud resources from within the cluster, you need the cluster id to look for the `kubernetes.io/cluster-name/cluster-id` tag.

**Comment by xiaomi7732** [comment]
@raelga Thanks for the info. Is this tag on the pods? If so, it is already recorded in the labels property.

@dewanymca Last time, we synced offline, talking about adding labels on to the node for the cluster name, did it work for you?

**Comment by dewanymca** [comment]
yes it did work for me

**Comment by raelga** [comment]
> @raelga Thanks for the info. Is this tag on the pods? If so, it is already recorded in the labels property.

Is not anywhere, the tag is only visible on the AWS resources (or at least I didn't find it anywhere).

```
❯ k get all --all-namespaces -o yaml | grep kubernetes.io/cluster | wc -l
       0
```

I'm writing an operator to manage some settings for AWS Network load balancers that are not manageble by the cloud provider controller. And the way I think the controller does is by filtering by two tags:

- `kubernetes.io/service-name": {namespace/servicename}`
- `kubernetes.io/cluster/{clusterIDTagKey}: "owned"`

So you can identify easily the resource using the ResourceGroupTagginAPI, but as `clusterIDTagKey` is not present anywhere. Finally I had to use the Service Ingress Hostname. (https://github.com/3scale/aws-nlb-helper-operator/issues/1). I would love to know how the actual AWS controller is using the tags, but I didn't found it anywhere.
