### ISSUE TITLE
Is the string interpolation in the telemetry initializer too heavy?

### ISSUE THREAD

**Issue by xiaomi7732** [microsoft/ApplicationInsights-Kubernetes#206]
@karolz-ms writes in https://github.com/microsoft/ApplicationInsights-Kubernetes/pull/205:

> Question unrelated to the change: does calling Invariant($"something something") incurs formatting and ToString() cost for every piece of telemetry that is augmented by KubernetesInitializer?

And that points to the code [here](https://github.com/microsoft/ApplicationInsights-Kubernetes/blob/822f927940899f6d629c76cd6b2ac619ab9eea01/src/ApplicationInsights.Kubernetes/TelemetryInitializers/KubernetesTelemetryInitializer.cs#L138). For example:

```csharp
SetCustomDimension(telemetry, Invariant($"{K8s}.{Container}.ID"), this._k8sEnvironment.ContainerID);
SetCustomDimension(telemetry, Invariant($"{K8s}.{Container}.Name"), this._k8sEnvironment.ContainerName);
```

On one hand, I often assumes string interpolation lightweight - not heavy at the least.
On the other hand, telemetry initializer are supposed to invoke very very frequently - and I assume that's why the question.

@karolz-ms could you please confirm my understand of your question? Also, do you have any quick suggestion? What do you think is the best way?

My experience is: for these kind of small string concatenating, using '+' operator + constants usually is the fastest method. The down side would be the readability of the code. Question then is: does it worth it? How much gain are we getting here?

What's your ideas?

**Comment by karolz-ms** [comment]
@xiaomi7732 yes that is what I was getting at. This code is on a hot path so even small costs add up.

In this particular case you have a dozen or so dimension names that could be pre-computed when the telemetry initializer is starting. Using a pre-computed string will always be faster than interpolation in terms of CPU load. Even more importantly, at least one avoidable memory allocation will be made for the result of the interpolation, per call.
