### ISSUE TITLE
Is it possible to use this library with worker services?

### ISSUE THREAD

**Issue by tomaszliptak** [microsoft/ApplicationInsights-Kubernetes#211]

**Comment by xiaomi7732** [comment]
@tomaszliptak In general, you might need to write some code for specific tracking, as long as you can use application insights, you will be able to use this library.
Just FYI, this might be a good start point: [Track Telemetry that's not automatically collected](https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core#how-can-i-track-telemetry-thats-not-automatically-collected).

**Comment by ncoussemacq** [comment]
Hi

I acutally have the same need. I have APIs and worker services running in different pods in AKS, all with ApplicationInsights-Kubernetes registered. 
Telemetry coming from APIs are properly tagged with kubernetes properties but my custom telemetry coming from background workers are not enriched with kubernetes properties. Any way to make this work ?

**Comment by xiaomi7732** [comment]
@ncoussemacq That is interesting. @ncoussemacq, do you mind providing more information for troubleshooting. Primarily need to understand how is the TelemetryConfiguration handled by:
1. Is it possible to share a copy of the worker code? If not:
2. Is it possible to share some code snippets around:
    1. How is application insights turned on?
    2. How is ApplicationInsights.Kubernetes (this library) turned on?
    3. How is the custom telemetry sent?
If you prefer to self-troubleshooting, refer to [instructions here](https://github.com/microsoft/ApplicationInsights-Kubernetes/blob/develop/docs/SelfDiagnostics.MD)

**Comment by xiaomi7732** [comment]
I have crated an example of `ApplicationInsights.Kubernetes` working in worker. PR submitted here:
https://github.com/microsoft/ApplicationInsights-Kubernetes/pull/250. Please see if it helps clear up the steps needed for it to work. Feel free to leave comment for clarification.

**Comment by xiaomi7732** [comment]
Please refer to [Application Insights Kubernetes Example (Worker)](https://github.com/microsoft/ApplicationInsights-Kubernetes/tree/develop/examples/WorkerExample) for how to make it work in workers.
Close this issue for now. Feel free to open new issues for any other questions.
