### ISSUE TITLE
Query Kubernetes Environment timeout.

### ISSUE THREAD

**Issue by amulya-pokala** [microsoft/ApplicationInsights-Kubernetes#214]
I am facing timeout issues with AI for kubernetes. Can anyone please give pointers on how to fix this

![image](https://user-images.githubusercontent.com/14961791/87932129-9d43bc80-caa8-11ea-98a5-b767cb4d9d33.png)
 
This is the piece of code that I have added

services.AddApplicationInsightsTelemetry();
			services.AddApplicationInsightsKubernetesEnricher(option => {
				option.InitializationTimeout = TimeSpan.FromSeconds(150);
			});
			var observer = new ApplicationInsightsKubernetesDiagnosticObserver(DiagnosticLogLevel.Error);
			ApplicationInsightsKubernetesDiagnosticSource.Instance.Observable.SubscribeWithAdapter(observer);

Even after I increased the timeout to 15min, I don't see things working

**Comment by xiaomi7732** [comment]
@amulya-pokala Does your cluster have RBAC on? Have you setup the proper service account like it here: [Setup the default Service Account for RBAC enabled cluster](https://github.com/microsoft/ApplicationInsights-Kubernetes/tree/develop/examples/BasicUsage_clr21_RBAC#setup-the-default-service-account-for-rbac-enabled-cluster)?

**Comment by amulya-pokala** [comment]
@xiaomi7732 the required role, rolebinding have already been assigned to the service accounts being used for this application

**Comment by xiaomi7732** [comment]
Hi @amulya-pokala thanks for the info. Could you please turn on the diagnostics and run it again:
https://github.com/microsoft/ApplicationInsights-Kubernetes/blob/develop/docs/SelfDiagnostics.MD
It will generate detailed logs around what is happening. If you want, post the logs here and I can help take a look what is going on.

**Comment by amulya-pokala** [comment]
> Hi @amulya-pokala thanks for the info. Could you please turn on the diagnostics and run it again:
> https://github.com/microsoft/ApplicationInsights-Kubernetes/blob/develop/docs/SelfDiagnostics.MD
> It will generate detailed logs around what is happening. If you want, post the logs here and I can help take a look what is going on.

[kube API logs.txt](https://github.com/microsoft/ApplicationInsights-Kubernetes/files/5068239/kube.API.logs.txt)

@xiaomi7732  PFA the text file that contains the logs generated for my application after running the diagnostics

**Comment by xiaomi7732** [comment]
Hi @amulya-pokala , thanks for sharing the logs. It looks like the enricher can't get the info to locate the current container id. **What is your base image for the container?**

There are 2 potential issues, either:
1. The format for container info in the cgroup is unexpected that the container id is not available.
2. If it is a windows container, there's no cgroup and additional configuration is needed, then.

**Comment by amulya-pokala** [comment]
> Hi @amulya-pokala , thanks for sharing the logs. It looks like the enricher can't get the info to locate the current container id. **What is your base image for the container?**
> 
> There are 2 potential issues, either:
> 
> 1. The format for container info in the cgroup is unexpected that the container id is not available.
> 2. If it is a windows container, there's no cgroup and additional configuration is needed, then.

Hey @xiaomi7732  the base image is microsoft/dotnet:2.2.1-aspnetcore-runtime-alpine3.8

**Comment by xiaomi7732** [comment]
Hey @amulya-pokala Could you please try update the RBAC settings like in this thread:
https://github.com/microsoft/ApplicationInsights-Kubernetes/issues/216
I suspect that you are caught by the same issue.

**Comment by amulya-pokala** [comment]
> Hey @amulya-pokala Could you please try update the RBAC settings like in this thread:
> #216
> I suspect that you are caught by the same issue.

hey @xiaomi7732  I have checked the cluster role binding yaml files and as mentioned in #216, the apigroup is already present.

The same clusterRole, rolebinding is being used by other apps in the same namespace and the kube AI is working for them. The only difference is that the other apps are on core 3.1 
Could that be an issue? since mine is on core 2.2 alpine image

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: devicecare-sa-node-reader-binding
subjects:
- kind: ServiceAccount
  name: devicecare-sa
  namespace: devicecare
roleRef:
  kind: ClusterRole
  name: sc-node-reader
  apiGroup: rbac.authorization.k8s.io


apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sc-node-reader
rules:
- apiGroups: ["*"]
  resources: ["nodes", "pods"]
  verbs: ["get", "watch", "list"]

**Comment by xiaomi7732** [comment]
Close this one due to no lack of activity. Feel free to file new issue if the problem is still there. Also, try out the fallback for getting container id: https://www.nuget.org/packages/Microsoft.ApplicationInsights.Kubernetes/2.0.3-beta1
