### ISSUE TITLE
Disable Performance Counters

### ISSUE THREAD

**Issue by pinkfloydx33** [microsoft/ApplicationInsights-Kubernetes#217]
Is it possible to disable the two performance counter metrics (CPU and Memory) from being added as telemetry properties by the telemetry initializers? The CPU always returns `NaN` and the memory always reports some wildly inaccurate value (ex. 11gb when in actuality it's more like 200mb). These two statistics clutter all of my telemetry. Since we have other means of monitoring them anyways, they are just a bunch of noise that causes undue alarm (in the case of the Memory).

These two items aren't really Kubernetes related. I was honestly quite surprised when I finally tracked down where they were coming from to see that it was this library. Can we please get a way to toggle these unrelated properties so that we can omit them from telemetry?

**Comment by xiaomi7732** [comment]
@pinkfloydx33 Thanks for the request. There's no way to configure the settings for now but I'll see if it can be added.

**Comment by xiaomi7732** [comment]
Keep this open until the new version is released.

**Comment by xiaomi7732** [comment]
Hi @pinkfloydx33 , the configuration is available at: 
https://www.nuget.org/packages/Microsoft.ApplicationInsights.Kubernetes/1.1.3

Refer to https://github.com/microsoft/ApplicationInsights-Kubernetes#configuration-details for how to use it.

**Comment by pinkfloydx33** [comment]
@xiaomi7732 thank you, and thanks for the quick turn around!
