### ISSUE TITLE
Current field naming enters in conflict with Kusto's data ingestion

### ISSUE THREAD

**Issue by feyanez** [microsoft/ApplicationInsights-Kubernetes#222]
Current naming convention for Kubernetes SDK's fields is not in compliance with the requirements by Kusto for data ingestion. In particular:
![image](https://user-images.githubusercontent.com/60495089/105251165-d8927700-5b2f-11eb-9d7d-a4992269550e.png)

For instance, in our case, the following fields are in conflict when Kusto attempts to create the tables since they were taken as "ID" and "Name" respectively. By having duplicate keys (i.e. different columns with same name), the table fails to be created.
![image](https://user-images.githubusercontent.com/60495089/105251400-4179ef00-5b30-11eb-92f3-aaa54b7a13ad.png)

As suggested from the Kusto team (see [IcM](https://portal.microsofticm.com/imp/v3/incidents/details/223704769/home) for more details), the owners of Kubernetes SDK should consider changing the naming of the fields to be underscore-separated instead of period-separated (e.g. "Kubernetes_Container_Name" instead of "Kubernetes.Container.Name"). Otherwise, it is needed to add the quotations as specified in the picture above.

Here is the [IcM](https://portal.microsofticm.com/imp/v3/incidents/details/221465008/home) on the Kubernetes SDK team for further reference.

After more than one month looking for the cause of the table-creation issue, I'm glad we are finally close to find a solution. Please let me know if you need any further information.

**Comment by xiaomi7732** [comment]
To address the issue like it above, a meaningful way, for an SDK, is to allow customization of the telemetry names.

Consider adding options like this to allow pre-process for telemetry names:
```csharp
services.AddApplicationInsightsKubernetesEnricher(opt => {
    opt.TelemetryKeyProcesser = (key) => {
        return key.Replace('.', '_');  // Or whatever you want to do to reshape the key.
    }
});
```

**Comment by xiaomi7732** [comment]
The feature is added in [1.1.4](https://www.nuget.org/packages/Microsoft.ApplicationInsights.Kubernetes/1.1.4). A wiki for the usage is here: [How to Customize Telemetry Property Names](https://github.com/microsoft/ApplicationInsights-Kubernetes/wiki/How-to-Customize-Telemetry-Property-Names).
