### ISSUE TITLE
Latest release takes a dependancy on some 5.0.0 and greater assemblies

### ISSUE THREAD

**Issue by buzzaII** [microsoft/ApplicationInsights-Kubernetes#228]
it seems the latest release takes some dependancies on these assemblies:

<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="5.0.1" />
<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="5.0.0" />

These failed to load as these required .net 5.0

**Comment by xiaomi7732** [comment]
Hi @buzzaII Thanks for filing the issue.

Yes, there are packages of 5.x. However, those packages works with `.NETStandard 2.0`. There is no requirement of .NET 5.

Is there a specific failure indicating the packages are not working? If there is, would you mind provide the runtime info for troubleshooting by running:

```bash
dotnet --info
```

**Comment by xiaomi7732** [comment]
And FYI, the dependencies are listed on NuGet:
[![image](https://user-images.githubusercontent.com/3674549/113602686-c0db7280-95f7-11eb-90a2-5c7e8c733312.png)](https://www.nuget.org/packages/Microsoft.ApplicationInsights.Kubernetes/2.0.0)

**Comment by buzzaII** [comment]
Found the issue - was due to Function App not loading up 5.0.0 aseemblies - thanks for the above info.

**Comment by xiaomi7732** [comment]
Oh~ Azure Function on Kubernetes wasn't in the picture.
@buzzaII Do I understand correct that your function app is a 3.x app and have dependencies on MS.Extensions.Configuration or MS.Extensions.DI 3.x.x, and since those were load first, runtime won't work when we try to load 5.x assemblies?

Does that mean you can't leverage AI.K8S (this package) until you upgrade the azure function app to 5.x? Will it address your problem if we downgrade the dependencies:
|Package|From|To|
|-|-|-|
|Microsoft.Extensions.Configuration|5.0.0|3.1.14|
|Microsoft.Extensions.DependencyInjection|5.0.1|3.1.14|
|Microsoft.Extensions.Options.ConfigurationExtensions|5.0.0|3.1.14|

How about `Microsoft.ApplicationInsights` since it currently relies on `System.Diagnostics.DiagnosticSource (>= 5.0.0)`? Is there a bound there?

**Comment by buzzaII** [comment]
> Oh~ Azure Function on Kubernetes wasn't in the picture.
> @buzzaII Do I understand correct that your function app is a 3.x app and have dependencies on MS.Extensions.Configuration or MS.Extensions.DI 3.x.x, and since those were load first, runtime won't work when we try to load 5.x assemblies?
> 
> Does that mean you can't leverage AI.K8S (this package) until you upgrade the azure function app to 5.x? Will it address your problem if we downgrade the dependencies:
> 
> Package	From	To
> Microsoft.Extensions.Configuration	5.0.0	3.1.14
> Microsoft.Extensions.DependencyInjection	5.0.1	3.1.14
> Microsoft.Extensions.Options.ConfigurationExtensions	5.0.0	3.1.14
> How about `Microsoft.ApplicationInsights` since it currently relies on `System.Diagnostics.DiagnosticSource (>= 5.0.0)`? Is there a bound there?

That is correct, I was looking at attempting this work with the older version in function apps, 

> Oh~ Azure Function on Kubernetes wasn't in the picture.
> @buzzaII Do I understand correct that your function app is a 3.x app and have dependencies on MS.Extensions.Configuration or MS.Extensions.DI 3.x.x, and since those were load first, runtime won't work when we try to load 5.x assemblies?
> 
> Does that mean you can't leverage AI.K8S (this package) until you upgrade the azure function app to 5.x? Will it address your problem if we downgrade the dependencies:
> 
> Package	From	To
> Microsoft.Extensions.Configuration	5.0.0	3.1.14
> Microsoft.Extensions.DependencyInjection	5.0.1	3.1.14
> Microsoft.Extensions.Options.ConfigurationExtensions	5.0.0	3.1.14
> How about `Microsoft.ApplicationInsights` since it currently relies on `System.Diagnostics.DiagnosticSource (>= 5.0.0)`? Is there a bound there?

Thats correct, Azure Functions will load System.Diagnostics.DiagnosticSource < 5.0.0 before this kicks in. Its used by a lot of the bindings like CosmosDB, Http etc.

I was attempting to get the previous working (< 2.0.0) in Azure functions but the way it DI configured itself wasn't compatible with:

https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection

Thanks for all your responses on this topic though, much appreciated.

**Comment by xiaomi7732** [comment]
Try new release:
https://www.nuget.org/packages/Microsoft.ApplicationInsights.Kubernetes/2.0.1
