### ISSUE TITLE
Customizing Telemetry Property Names

### ISSUE THREAD

**Issue by v-shaaal** [microsoft/ApplicationInsights-Kubernetes#230]
### Question:
Using Application Insights Kubernetes Enricher adds a few properties to the logs. Some of these are as follows:

- Kubernetes.Container.ID
- Kubernetes.Container.Name
- Kubernetes.Pod.ID
- Kubernetes.Pod.Labels
- Kubernetes.Pod.Name
- Kubernetes.Pod.Namespace

Is it possible to customize these property names?

### Why?
Our team is forwarding the Geneva logs to Kusto. Kusto, while ingesting the data, trims off the property name if there is a dot in it. So the aforementioned properties become the following:

- ID
- Name
- ID
- Labels
- Name
- Namespace

This trimming causes the conflict in names hence the data does not flow from Geneva to Kusto. If the names or the connector was customizable, we could use `_` instead of `.`. Does the enricher have any such capability, or is there a plan to add such support?

Thanks!

**Comment by rogordon01** [comment]
The feature is added in [1.1.4](https://www.nuget.org/packages/Microsoft.ApplicationInsights.Kubernetes/1.1.4). A wiki for the usage is here: [How to Customize Telemetry Property Names](https://github.com/microsoft/ApplicationInsights-Kubernetes/wiki/How-to-Customize-Telemetry-Property-Names).

**Comment by v-shaaal** [comment]
Thank you! This helps!
