### ISSUE TITLE
GitHub release (or tag) 2.0.1 is missing

### ISSUE THREAD

**Issue by 304NotModified** [microsoft/ApplicationInsights-Kubernetes#234]
There is a NuGet package with version 2.0.1 but the latest GitHub release is 2.0.0

**Comment by xiaomi7732** [comment]
@304NotModified Thanks for pointing that out. While I am trying to figure out which commit to tag it on, would you mind let us understand why those tags are important?

**Comment by xiaomi7732** [comment]
Anyway, new released added: <https://github.com/microsoft/ApplicationInsights-Kubernetes/releases/tag/2.0.1>

**Comment by 304NotModified** [comment]
Thanks!

The reason I asked:
- changelings are important for upgrading
- I think it's important to trace the implementation changes (e.g. for security)
- I think it's important to keep the NuGet and GitHub releases in sync. Otherwise it's a bit confusing
