### ISSUE TITLE
Is it possible to choose which properties to log into ApplicationInsight ?

### ISSUE THREAD

**Issue by macpak** [microsoft/ApplicationInsights-Kubernetes#242]
I can't find this but is it possible to log only specific properties ? (like pod/container name only)

**Comment by xiaomi7732** [comment]
@macpak, there's currently no way to specify which properties to include, it is all or nothing. That said, would you mind explain why would you not wanting some of the properties being there?
Thanks!

**Comment by macpak** [comment]
Generally, I'd like to have all of them :) 
The problem is that in our case, we do not have all the permissions to get all propertes.

When I enabled diagnostics, I saw some failed requests with HTTP 403.  Additiionally, it seems that when some properties can't be obtained, no logs are pushed to ApplicationInsights (at least that's what I've observed).

**Comment by xiaomi7732** [comment]
All the properties are made optional except the Pod. Please check out https://www.nuget.org/packages/Microsoft.ApplicationInsights.Kubernetes/2.0.6-beta1
Or
https://www.nuget.org/packages/Microsoft.ApplicationInsights.Kubernetes/3.0.0-beta2
