### ISSUE TITLE
Any plans to support .Net Framework 4.8

### ISSUE THREAD

**Issue by magedfarag** [microsoft/ApplicationInsights-Kubernetes#245]
Dears,

I'm running a critical application on .Net Framework 4.8, and hosted on AKS Windows Container, are there is any alternatives or version that provide same functionalities for Windows Containers ?

**Comment by xiaomi7732** [comment]
Hi @magedfarag Thanks for the ask. This library is built on .NET Standard 2.0 and should work on .NET Framework 4.8 on Windows container already. Refer to this example:

https://github.com/microsoft/ApplicationInsights-Kubernetes/tree/develop/examples/WindowsContainer

**Comment by xiaomi7732** [comment]
Feel free to open issues if there's any concrete issue.
