### ISSUE TITLE
Disable Performance Counters

### ISSUE THREAD

**Issue by NivedhaL20** [microsoft/ApplicationInsights-Kubernetes#248]
I have enabled Application Insights for Kubernetes using the below code snippet in Startup.cs

services.AddApplicationInsightsTelemetry();
**services.AddApplicationInsightsKubernetesEnricher(opt =>
                opt.DisablePerformanceCounters = true
            );** 

I tried to disable performance counters which insert records in Perf Table. But I could not able to disable using the above code. 

Please do help as soon as possible.

**Comment by xiaomi7732** [comment]
Hi @NivedhaL20 , are you looking for ways to turn off Performance Counters for environment? Is it windows container?

Please help me understand what your goal is.

Basically, AI.K8s doesn't control the enable/disable of perf counters. It gathers and set value to the Telemetry object in application insights, and when you set `DisablePerformanceCounters`, it means: do not gather or set the value for CPU/memory usage to the telemetries.

Could you please explain more about `insert records in Perf Table`? Ideally, post a screenshot with the data you don't want.

**Comment by xiaomi7732** [comment]
@NivedhaL20 I see. I think you are trying to disable performance counter gathering totally. That is not controlled by AI.K8s. We need to find the proper owner to see if that is doable. @TimothyMothra, do you know whom shall we contact for help?

**Comment by xiaomi7732** [comment]
@NivedhaL20 The core application insights SDK is the right team. Please open an issue with them:
https://github.com/microsoft/ApplicationInsights-dotnet/issues/new/choose

If possible, it would be great if you could link back the info to the new issue here. Thank you!

**Comment by xiaomi7732** [comment]
Close this one for now. Feel free to open new issues.

**Comment by NivedhaL20** [comment]
Thanks @xiaomi7732.. 👍
