### ISSUE TITLE
Is this extension supported on AKS with Windows nodes?

### ISSUE THREAD

**Issue by drauch** [microsoft/ApplicationInsights-Kubernetes#251]
I'm not sure about it due to #172 , do we have to add some additional configuration not shown in the sample code? Does it "just work"?

Best regards,
D.R.

**Comment by drauch** [comment]
OK, thank you, sounds great!

One question though:
```
<PublishWithAspNetCoreTargetManifest>false</PublishWithAspNetCoreTargetManifest>
```
Why is that needed? According to the official docs, this is a property for .NET Core 2.x only, do we need it with 6.x too?

**Comment by drauch** [comment]
In https://github.com/dotnet/aspnetcore/issues/3310#issuecomment-404986286 they even say that support for this property has been removed.

**Comment by xiaomi7732** [comment]
Hey @drauch Thanks for noticing that. That is correct that it is not needed any more if you are using .NET Core 2.1 +, and surely for .NET 6. I am thinking about putting a tip/notes in the example documentation to state it clearly.

Do you want to submit a PR for it? Or I can update it. Let me know. Thanks again for noticing it.

**Comment by drauch** [comment]
Unfortunately I don't have the time for a PR.

**Comment by xiaomi7732** [comment]
Thanks for the reply. I'll submit one. Thank you again for the feedback!

**Comment by xiaomi7732** [comment]
PR submitted. I'll close this issue since there's no other immediate action. Feel free to open new issues.
