### ISSUE TITLE
Compliance: Unit test SDK depends on Newtonsoft.Json 9.0.1

### ISSUE THREAD

**Issue by xiaomi7732** [microsoft/ApplicationInsights-Kubernetes#329]
Dependency graph:

![image](https://user-images.githubusercontent.com/3674549/197864074-0a34925c-d7dd-49b0-926b-903c31da3f61.png)

It looks like an option is to bump the unit test SDK to [17.4.0-preview-20220707-01](https://www.nuget.org/packages/Microsoft.TestPlatform.TestHost/17.4.0-preview-20220707-01) or above, that will carry a version of Newtonsoft.Josn >= 13.0.0

Considering it is unit tests only, the production package doesn't depend on it, another option might be to hold still until there's a newer stable version of the test SDK.

**Does anyone see an urgent to upgrade it immediately?** There's also an option to directly depend on the latest version of `Newtonsoft.Json` in the unit test project.

**Comment by xiaomi7732** [comment]
Tagging @JacobBovee , @karolz-ms too. Does either of you have any preference?

**Comment by karolz-ms** [comment]
No strong preference since this is test code. Bumping the test SDK to 17.4+ might be the safest option if you decide to fix it now, as opposed to waiting.
