### ISSUE TITLE
Use AKS instead of local kubernetes - How

### ISSUE THREAD

**Issue by eliassal** [microsoft/ApplicationInsights-Kubernetes#339]
Hi, can you please let me know how can I adapt the procedure to use AKS instead of local kubernetes? 
I have ACR and I was able to push the image to it, not sure what should be the next steps to deploy to AKS.
Thanks

**Comment by xiaomi7732** [comment]
Hi @eliassal, Thanks for contacting us. Do you have a specific question for Application Insights for Kubernetes or are you asking generally, how to host your containers in AKS?

If it is the prior, please state the specific issue, like what is your expectation vs what was not working.
If it is the latter, I would suggest you start with the official tutorial: https://learn.microsoft.com/en-us/azure/aks/tutorial-kubernetes-prepare-app

Please let me know if that helps.

**Comment by eliassal** [comment]
Exact, I followed the steps indicated at  https://learn.microsoft.com/en-us/azure/aks/tutorial-kubernetes-prepare-app ut I used your apps and yaml files, after deployment, in AKS I have 

![image](https://user-images.githubusercontent.com/8447864/218538286-a5f1036b-1b1c-4696-98df-599bd0cfd4ad.png)

when I dig, I see "ImagePullBackOff" as follows

I followed troubleshooting at  https://learn.microsoft.com/en-us/troubleshoot/azure/azure-kubernetes/cannot-pull-image-from-acr-to-aks-cluster
 what is strange is that when I exceute

`az aks show --resource-group my-RG --name myKSCluster --query servicePrincipalProfile.clientId --output tsv`

I get
![image](https://user-images.githubusercontent.com/8447864/21853903yrtsigery7-5c7dd79e-8fcc-4f78-8f21-1edd0ad3fc2c.png)

whereas executing 

az role assignment list --scope /subscriptions/XXXXXXXXXXe3b-82512dfda843/resourceGroups/my-RG/providers/Microsoft.ContainerRegistry/registries/myACR 
I get

> Principal                             Role     Scope
> ------------------------------------  -------  ---------------------------------------------------------------------------------------------------------------------------------------------------------
> 8c07666d-XXXX-XXXX-XXXXX-b0aacbd4b6b5  AcrPull  /subscriptions/f151ee3f-4725-460d-8e3b-82512dfda843/resourceGroups/my-RG/providers/Microsoft.ContainerRegistry/registries/myACR

so what is missing? I thought that sa-role.yaml should be enoughyto fix the RBAC access. Wjhat m I missing?

Also, it is indicated in the troubleshooting page to 

_Compare the two service principals. If they don't match, integrate the AKS cluster with the container registry again._

How this can be done in our scenao?

**Comment by xiaomi7732** [comment]
There are 2 things - it looks like your K8s cluster doesn't have permission to pull from your ACR, that you will need to have proper permissions setup. The RBAC configuration in this repo will not help address that issue.

**Comment by xiaomi7732** [comment]
Please refer to [Authenticate with Azure Container Registry from Azure Kubernetes Service](https://learn.microsoft.com/en-us/azure/aks/cluster-container-registry-integration?tabs=azure-cli) for how to set up permissions so that AKS can pull from ACR.
I'll close this issue now since there are no actionable items in this repo.
