### ISSUE TITLE
Enhancement: Capture container image name

### ISSUE THREAD

**Issue by aforank** [microsoft/ApplicationInsights-Kubernetes#342]
Image name is one of the critical parameters to check when something goes wrong. I know I can get the image name by first referring to a pod Id, then query the cluster and find out the image name. But as you see it is a two way step now to get that tiny information. 

Therefore, it would be better to capture the image name along with other telemetry properties.

**Comment by xiaomi7732** [comment]
@aforank Thanks for the proposal. I think it makes sense. Do you want to submit a PR for it?

**Comment by aforank** [comment]
@xiaomi7732 xiaomi7732 Yes, I can submit a PR... You may assign it to me for tracking purposes.

**Comment by xiaomi7732** [comment]
Perfect! Looking forward to it.

**Comment by xiaomi7732** [comment]
@aforank, your code is released in 6.1.1-beta1 here: 
https://www.nuget.org/packages/Microsoft.ApplicationInsights.Kubernetes/6.1.1-beta1

Please check it out and let us know.

**Comment by xiaomi7732** [comment]
@aforank, you are welcome! I'll close this issue for now. Feel free to file new ones.
