### ISSUE TITLE
As of now the package doesn't seem to add the properties anymore?

### ISSUE THREAD

**Issue by drauch** [microsoft/ApplicationInsights-Kubernetes#354]
**Describe the bug**
The documented additional properties do not show up in Application Insights.

**Package Versions**
Application Insights Kubernetes Version: 6.1.1
Application Insights SDK Version: 2.21.0

**Additional context**
We're running on .NET 7.

Best regards,
D.R.

**Comment by xiaomi7732** [comment]
Hi @drauch Do you mind turning on the trace logging and posting a copy of it here? With that, we can start troubleshooting.

```csharp
builder.Services.AddApplicationInsightsKubernetesEnricher(LogLevel.Trace);
```

**Comment by drauch** [comment]
Thanks for the hint for trace logging, we realized that the permissions for the API server were not correctly set. Issue can be closed.

**Comment by xiaomi7732** [comment]
Cool!
