### ISSUE TITLE
how to customize k8s properties name 

### ISSUE THREAD

**Issue by renukajataprolu** [microsoft/ApplicationInsights-Kubernetes#359]
How to customize properties names namespace,PodName,NodeName

**Comment by renukajataprolu** [comment]
Has any one tried customizing properties Kubernetes.Pod.Namespace to Namespace

**Comment by xiaomi7732** [comment]
Hi @renukajataprolu , is this what you are looking for:
https://github.com/microsoft/ApplicationInsights-Kubernetes/wiki/How-to-Customize-Telemetry-Property-Names

**Comment by xiaomi7732** [comment]
Close since there's no response for a couple of days. Please feel free to file a new issue if there's anything new. Thanks.
