### ISSUE TITLE
Transitive vulnerable dependencies v7.0.0

### ISSUE THREAD

**Issue by almegdad** [microsoft/ApplicationInsights-Kubernetes#365]
**Describe the bug**
Transitive vulnerable packages needs to be upgraded for Microsoft.ApplicationInsights.Kubernetes and Microsoft.ApplicationInsights.Kubernetes.HostingStartup packages

**Package Versions**
Application Insights Kubernetes Version: 7.0.0
Application Insights SDK Version: 7.0.0

**To Reproduce**
run command: **dotnet list package --include-transitive --vulnerable**

Project `ApplicationInsights.Kubernetes` has the following vulnerable packages
   [net6.0]:
   Transitive Package                           Resolved   Severity   Advisory URL
   > Microsoft.IdentityModel.JsonWebTokens      7.0.0      Moderate   https://github.com/advisories/GHSA-59j7-ghrg-fj52
   > System.IdentityModel.Tokens.Jwt            7.0.0      Moderate   https://github.com/advisories/GHSA-59j7-ghrg-fj52

Project `UnitTests` has the following vulnerable packages
   [net6.0]:
   Transitive Package                           Resolved   Severity   Advisory URL
   > Microsoft.IdentityModel.JsonWebTokens      7.0.0      Moderate   https://github.com/advisories/GHSA-59j7-ghrg-fj52
   > System.IdentityModel.Tokens.Jwt            7.0.0      Moderate   https://github.com/advisories/GHSA-59j7-ghrg-fj52
   > System.Net.Http                            4.3.0      High       https://github.com/advisories/GHSA-7jgj-8wvc-jh57
   > System.Text.RegularExpressions             4.3.0      High       https://github.com/advisories/GHSA-cmhx-cq75-c4mj

Project `ApplicationInsights.Kubernetes.HostingStartup` has the following vulnerable packages
   [net6.0]:
   Transitive Package                           Resolved   Severity   Advisory URL
   > Microsoft.IdentityModel.JsonWebTokens      7.0.0      Moderate   https://github.com/advisories/GHSA-59j7-ghrg-fj52
   > System.Drawing.Common                      4.7.0      Critical   https://github.com/advisories/GHSA-rxg9-xrhp-64gj
   > System.IdentityModel.Tokens.Jwt            7.0.0      Moderate   https://github.com/advisories/GHSA-59j7-ghrg-fj52

**Expected behavior**
transitive vulnerable packages needs to be resolved.

**Additional context**
to fix the issue:
1) Project: `ApplicationInsights.Kubernetes`
upgrade `KubernetesClient` package from version `12.1.1` to `13.0.11`
2) Project: `ApplicationInsights.Kubernetes.HostingStartup`
upgrade `Microsoft.ApplicationInsights.AspNetCore` package from version `2.21.0` to `2.22.0`
3) Project `UnitTests`
upgrade `xunit` and `xunit.runner.visualstudio` from version `2.4.* `to `2.6.*`

**Comment by xiaomi7732** [comment]
To balance between the backward compatibility with security, deep investigation is needed. Here's some dependnecy chain info:

For JWT tokens:
![image](https://github.com/microsoft/ApplicationInsights-Kubernetes/assets/3674549/04d05c54-5a03-4b03-ad47-63c3813ce365)

**Comment by xiaomi7732** [comment]
For the unit test project, it looks like System.Net.Http/4.3.0 is brought in by NETStandard1.6:
![image](https://github.com/microsoft/ApplicationInsights-Kubernetes/assets/3674549/33d9a2bf-e652-4163-ab69-f896027367c2)

**Comment by xiaomi7732** [comment]
Bump up the targer version of applicaiton insights from 2.21 to 2.22 makes sense.

**Comment by xiaomi7732** [comment]
After the upgrade:

PS C:\Repos\fork-ai-k8s> dotnet list package --include-transitive --vulnerable

The following sources were used:
   https://api.nuget.org/v3/index.json

The given project `ApplicationInsights.Kubernetes` has no vulnerable packages given the current sources.
The given project `UnitTests` has no vulnerable packages given the current sources.
The given project `ApplicationInsights.Kubernetes.HostingStartup` has no vulnerable packages given the current sources.

**Comment by xiaomi7732** [comment]
Check out the package: https://www.nuget.org/packages/Microsoft.ApplicationInsights.Kubernetes/7.0.1-beta1
