### ISSUE TITLE
Redis Telemetry not appearing on Application Insights

### ISSUE THREAD

**Issue by adeelakhan** [microsoft/ApplicationInsights-Kubernetes#368]
**Describe the bug**
When reviewing the application map for a dotnet application hosted on AKS we noticed no telemetry to redis endpoints/dependency. Case #2407250010001728 was raised with Microsoft and MS engineer advised to raise a case directly with engineering as they don't support this package.

**Package Versions**
Application Insights Kubernetes Version: 7.0.0
Application Insights SDK Version: 2.22.0

**To Reproduce**
1. Go to Application Insights for the specific AKS cluster.
2. Click on Application Map.
3. Redis Dependency does not appear on the map although the highest amount of traffic is sent/received from that endpoint.

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/4fe30359-882f-4e19-a52f-cb4c4447711e)
![image](https://github.com/user-attachments/assets/8f84ec8e-276b-46e6-a7c4-38ff5789b053)

![image](https://github.com/user-attachments/assets/af910d0c-87d1-4364-bcd6-176c884038ff)

**Additional context**
Microsoft support email pasted below,
Hi Adeel,

Thanks for your time, I really appreciate your cooperation. 
We have discussed the symptom on the meeting and provided a suggestion, please kindly refer to following meeting minutes for your reference:

Symptom
=======
Application Map not showing all endpoints such as [lwccachesydney.redis.cache.windows.net](https://urldefense.com/v3/__http:/lwccachesydney.redis.cache.windows.net__;!!MfzFaTml5A!iR7kHzZ7Zwx_vJebxJ-aVkgnzDsD7iioMvbCw37EY-AZncmHUEDNfDEz4UWHopPHT61NpILpmn0-EoGYzW7XIXBOKg$)
 

Analysis
======
Application Map will visualize two telemetry type requests and dependency.
We have queried Redis log over the past 7 days, there is no record being captured which is why the Redis didn’t appear in the Application Map.
 
 

By checking the telemetry further, we found that SDK version is ai-K8S[7.0.0.0](https://urldefense.com/v3/__http:/7.0.0.0__;!!MfzFaTml5A!iR7kHzZ7Zwx_vJebxJ-aVkgnzDsD7iioMvbCw37EY-AZncmHUEDNfDEz4UWHopPHT61NpILpmn0-EoGYzW4bp5m53g$) and all those telemetries were captured by ai-k8s:x.x.x.x
 

As per your developer team’s confirmation, they added package <PackageReference Include="Microsoft.ApplicationInsights.Kubernetes" Version="7.0.0" /> in the source code.
I have double checked this version with our K8S team and engineering team, Unfortunately, I was told that this specific SDK is beyond CSS knowledge and scope, it is supported by our engineering team directly.

Suggestion
=======
To address this issue further, please kindly ask your developer team to raise this question on GitHub.
[GitHub - microsoft/ApplicationInsights-Kubernetes: Enrich the telemetry data for .NET applications running inside containers that are managed by Kubernetes.](https://urldefense.com/v3/__https:/github.com/microsoft/ApplicationInsights-Kubernetes__;!!MfzFaTml5A!iR7kHzZ7Zwx_vJebxJ-aVkgnzDsD7iioMvbCw37EY-AZncmHUEDNfDEz4UWHopPHT61NpILpmn0-EoGYzW6cXWLDWQ$)

Hope this makes sense for you and kindly let me know if you have further questions.

Regards,
Jason

**Comment by xiaomi7732** [comment]
Hi @adeelakhan , this is not the correct repository for this issue. Could you please file an new issue there:
https://github.com/microsoft/ApplicationInsights-dotnet.

**Comment by xiaomi7732** [comment]
Question answered there. Close this one.
