### ISSUE TITLE
Error 'Application is not running inside a Kubernetes cluster' in AKS pod's logs

### ISSUE THREAD

**Issue by ReySka91** [microsoft/ApplicationInsights-Kubernetes#370]
**Description**
We are running ApplicationInsights.Kubernetes with our microservices in AKS. 
We take the tool into use like this:
            _services.AddApplicationInsightsTelemetry();
            services.AddApplicationInsightsKubernetesEnricher();_

We have configured RBAC permissions according to [this guide](https://github.com/microsoft/ApplicationInsights-Kubernetes/blob/develop/docs/configure-rbac-permissions.md). 

For some reason, the tool does not work at all. 

We have run the troubleshooter tool without any issues using the same versions as our main applicaion. We have enabled the diagnostics with _services.AddApplicationInsightsKubernetesEnricher(LogLevel.Trace);_. The only message related to this tool in the pod's logs is: _[Error] [2024-10-03T10:23:15.6375636Z] Application is not running inside a Kubernetes cluster._. 

**Package Versions**
Application Insights Kubernetes Version: 7.0.0
Application Insights SDK Version: 2.22.0
.NET Core Version: 8

**Expected behavior**
The tool works without errors and the additional information is shown in application insights

**Actual bevior**
The tool fails on error 'Application is not running inside a Kubernetes cluster' even though it is running in AKS.

Can you please help with this issue? I'm not sure whether this is a bug or just a misconfiguration or if it has something to do with our versions (even though the troubleshooter works with the same versions)

**Comment by xiaomi7732** [comment]
@ReySka91, in the latest version, the check is straightforward:
https://github.com/microsoft/ApplicationInsights-Kubernetes/blob/81610ab2d76e337c3db0163aa0f65c4b531a729b/src/ApplicationInsights.Kubernetes/ClusterEnvironmentCheck.cs#L7
That, in turn, calls:
https://github.com/kubernetes-client/csharp/blob/541abb00bd1472e86b37863822cce5415613806b/src/KubernetesClient/KubernetesClientConfiguration.InCluster.cs#L21

Basically, do you see any of these line of code returning false for your environment:

```csharp
        public static bool IsInCluster()
        {
            var host = Environment.GetEnvironmentVariable("KUBERNETES_SERVICE_HOST");
            var port = Environment.GetEnvironmentVariable("KUBERNETES_SERVICE_PORT");

            if (string.IsNullOrEmpty(host) || string.IsNullOrEmpty(port))
            {
                return false;
            }

            var tokenPath = Path.Combine(ServiceAccountPath, ServiceAccountTokenKeyFileName);
            if (!FileSystem.Current.Exists(tokenPath))
            {
                return false;
            }

            var certPath = Path.Combine(ServiceAccountPath, ServiceAccountRootCAKeyFileName);
            return FileSystem.Current.Exists(certPath);
        }
```

**Comment by xiaomi7732** [comment]
Close due to no response. Feel free to reopen if there's more info.
