### ISSUE TITLE
Any plan for Swarm Mode?

### ISSUE THREAD

**Issue by alexsandro-xpt** [Microsoft/ApplicationInsights-Kubernetes#68]
Will be awesome.....

**Comment by xiaomi7732** [comment]
Thanks for the feedback. Please give me some time to investigate it.

**Comment by brahmnes** [comment]
There is still a good amount to improve on for Kubernetes, so we probably won't get to Swarm anytime soon.

**Comment by alexsandro-xpt** [comment]
Ok
