### ISSUE TITLE
When will be beta2 release?

### ISSUE THREAD

**Issue by SychevIgor** [Microsoft/ApplicationInsights-Kubernetes#74]
Hello,
latest release on a nuget was in May 2017. As I can see we have some changes. Maybe it's time to release some beta2 version for dev who already invest sometime and tested this package in their apps  earlier?

**Comment by brahmnes** [comment]
Agree with you suggestion.
Weill looks at releasing this week or next.

**Comment by xiaomi7732** [comment]
@SychevIgor , please find the beta2 release here:
https://www.nuget.org/packages/Microsoft.ApplicationInsights.Kubernetes/1.0.0-beta2

Thanks!
