### ISSUE TITLE
Daemonset/sidecar container?

### ISSUE THREAD

**Issue by raghur** [Microsoft/ApplicationInsights-Kubernetes#78]
So at the outset, I have only basic understanding of appinsights's data model. However, I'm currently working on porting a relatively mid sized codebase to .net core with the aim to run it on k8s. Also, I've just landed on your repo from google and a quick read through isn't very informative - however, it did bring up a question. 

The question I have is that would it be possible to explore running this as a sidecar/daemonset in k8s - so that the actual code doesn't have to deal with keeping a buffer/flush it's log etc. Even better if this can also take an [eventflow config](https://github.com/Azure/diagnostics-eventflow) and be responsible for pushing AI telemetry reliably.

**Comment by xiaomi7732** [comment]
@raghur,
Thanks for bringing the question up.

Firstly, let me see if I understand what you are asking here. Are you trying to see if we can host **something** as a service in the sidecar, so that your application throws whatever the events interested to the sidecar? The sidecar handles the communication with application insights server.

If I got that correct, the short answer would be no, we don't support sidecar hosting at this point. However, could you please explain your diagnose requirements, like what are the info that your interested if there's a sidecar running?

Thanks again for your asking.

**Comment by raghur** [comment]
@xiaomi7732 what I'm trying to as is something like this:
 >Firstly, let me see if I understand what you are seeking. Are you trying to see if we can host something as a service in the sidecar, so that your application throws whatever the events interested to the sidecar? The sidecar handles the communication with application insights server.

Yes 

> like what are the info that your interested if there's a sidecar running?

So one thing that I'd love to see is basically node information (cpu/memory etc) correlated with application events. today to achieve that, I'm relying on what K8S downward api provides (node name etc) to add on as additional kv pairs but the info is limited and I don't want to write any code for that. It'd be great if something like this can a) recieve log events from the app, b)additionally enrich/filter/transform  using eventflow diagnostics and c) enrich with node info so that application events can be correlated with node events in AI. 

I recently [asked about APM options](https://www.reddit.com/r/dotnet/comments/7ljuvt/apm_for_dot_net_core_app_on_kubernetes/) for .net core apps on k8s on reddit. That's sort of what I'm after and basically describes my diagnostic requirements.

**Comment by xiaomi7732** [comment]
@raghur, thank you for providing the details.
In short term for this project, we shall be able to provide the CPU/memory info on app events per https://github.com/dotnet/standard/issues/327.

Now, I understand that by itself will not address all your requirements, we are working on to provide more comprehensive solutions, which, I am sorry, I don't have too many details to share at this point. You will see more & more diagnostics support down the line.

All that said, I'll use this issue to track the work to add basic metrics (CPU & memory) to Application Insights events.

Thanks again for the feedback and feel free to let me know if there's more question.

**Comment by xiaomi7732** [comment]
@raghur Since there will be no further action taken in the foreseeable future, I will close this issue. Please keep an eye on Microsoft's application insights solution for Kubernetes.
