### ISSUE TITLE
Enable Application insights for .net application

### ISSUE THREAD

**Issue by girishgouda** [Microsoft/ApplicationInsights-Kubernetes#91]
Hi 
We want to use the application insights for .net framework web application running in kubernetes

Thanks
Girish

**Comment by xiaomi7732** [comment]
@girishgouda,
Thanks for your asking. There are several aspects of the question and depends on your clarification & expectation, the answer differs.

Please help me understand more about your requirements by answering the following questions:
1. Are you running ASP.NET Web Application in a windows container with full .NET Framework? If it is not, could you please explain more about how are you running your application inside Kubernetes?
2. Are you hosting your containers in Azure Container Service? If not, where are you hosting the service?
3. What is the target .NET Framework version?
4. What do you expect out of application insights? To be specific, do you want to have the ability to send telemetry data into application insights or do you want to have the advanced features like seeing your service relationships in AppMap? Have you tried to use the .NET Fx version of application insights here: https://github.com/Microsoft/ApplicationInsights-dotnet-server? Does that fulfill your requirement? If not, what is the gap?
5. Could you please generally describe what's your telemetry requirement?

Thanks,
Saar

**Comment by girishgouda** [comment]
Following are the comments
1) Yes we want to showcase our customer running full .net framework in kubernets to use application insights 

2)Yes -ACS

3)3.5 and 4.5

4)We want to capture the request failed like 400 errors and take action based on that 

5) Check any failures and take action based on that 

Thanks
Girish

**Comment by xiaomi7732** [comment]
@girishgouda Thanks for your info. For traditional ASP.NET Web Application running in Windows Container, I think you shall be able to use Application Insights for .NET directly here:
* https://docs.microsoft.com/en-us/azure/application-insights/app-insights-asp-net.

If you have further question, please file an issue in this github repo:
* https://github.com/Microsoft/ApplicationInsights-dotnet-server

Let me know if there's anything else I can help.

Thanks!

**Comment by xiaomi7732** [comment]
Close this issue since there are no recent activities on this.
